# {build} is required by AppVeyor to uniquely identify its builds on the url
# It is a continuously incrementing number so when used it violates the reset
# smaller build parts rule of semantic versioning. Therefore we introduce a
# second environment variable semantic_version.
version: 0.6.1.{build}

os: Visual Studio 2015

environment:
  RunCodeAnalysis: true
  version_readmodel: 0.6.4
  version_readmodelmongo: 0.6.4

configuration:
  - Debug
  - Release

cache:
  - packages -> **\packages.config

services:
  - mongodb

install:
  - set semantic_version=%APPVEYOR_BUILD_VERSION:~0,5%
  - echo Version - %semantic_version%
  - nuget restore

nuget:
  disable_publish_on_pr: true

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(semantic_version).{build}'
  assembly_file_version: '$(semantic_version).{build}'
  assembly_informational_version: '$(semantic_version)'

build:
  project: Build.proj
  parallel: true
  verbosity: normal

after_test:
  - nuget pack "%APPVEYOR_BUILD_FOLDER%\ReadModel\ReadModel.nuspec" -BasePath "%APPVEYOR_BUILD_FOLDER%\ReadModel\bin\%configuration%" -Properties "Configuration=%configuration%;Platform=%platform%;Version=%version_readmodel%" -OutputDirectory "%TEMP%" -Verbosity detailed
  - appveyor PushArtifact "%TEMP%\Spritely.ReadModel.%version_readmodel%.nupkg"
  - nuget pack "%APPVEYOR_BUILD_FOLDER%\ReadModel.Mongo\ReadModel.Mongo.nuspec" -BasePath "%APPVEYOR_BUILD_FOLDER%\ReadModel.Mongo\bin\%configuration%" -Properties "Configuration=%configuration%;Platform=%platform%;Version=%version_readmodelmongo%" -OutputDirectory "%TEMP%" -Verbosity detailed
  - appveyor PushArtifact "%TEMP%\Spritely.ReadModel.Mongo.%version_readmodelmongo%.nupkg"

deploy:
  - provider: NuGet
    on:
      branch: master
      configuration: Release
    api_key:
      secure: dUMLXnYuqF7ORswtDCtj2XgKlpLMKrXZrq9m/FEN2xu0vTClejXqADyxMEawTs2W
    skip_symbols: true
    artifact: /.*\.nupkg/
